// <auto-generated />
namespace GetRate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TransportationTypedeleted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TransportationTypedeleted));
        
        string IMigrationMetadata.Id
        {
            get { return "202308252019359_TransportationType deleted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
