// <auto-generated />
namespace GetRate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RoutePoint2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoutePoint2));
        
        string IMigrationMetadata.Id
        {
            get { return "202308111625068_RoutePoint2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
